# Linear Algebra : Vectors and Matrices 

##  Vectors 

In [11]:
# create a vector
from numpy import array
# define vector
v = array([1, 2, 3])
print(v)

[1 2 3]


### 1) Addition 

In [2]:
# vector addition
from numpy import array
# define first vector
a = array([1, 2, 3])
print("print the first vector",a)
# define second vector
b = array([1, 2, 3])
print("print the second vector",b)
# add vectors
c = a + b
print("c = a + b is : ",c)

print the first vector [1 2 3]
print the second vector [1 2 3]
c = a + b [2 4 6]


### 2) Subtraction 

In [4]:
# vector subtraction
from numpy import array
# define first vector
a = array([1, 2, 3])
print("The first vector a", a)
# define second vector
b = array([0.5, 0.5, 0.5])
print("The second vector b",b)
# subtract vectors
c = a - b
print("c = a-b is : ", c)

The first vector a [1 2 3]
The second vector b [0.5 0.5 0.5]
c = a-b is :  [0.5 1.5 2.5]


### 3) Multiplication 

In [5]:
# vector multiplication
from numpy import array
# define first vector
a = array([1, 2, 3])
print("The first vector : ",a)
# define second vector
b = array([1, 2, 3])
print("The second vector :",b)
# multiply vectors
c = a * b
print(" c = a*b ",c)

The first vector :  [1 2 3]
The second vector : [1 2 3]
 c = a*b  [1 4 9]


### 4) Division 

In [9]:
# vector division
from numpy import array
# define first vector
a = array([1, 2, 3])
print("The first vector : ",a)
# define second vector
b = array([1, 2, 3])
print("The second vector : ",b)
# divide vectors
c = a / b
print(" c = a/b is : ",c)

The first vector :  [1 2 3]
The second vector :  [1 2 3]
 c = a/b is :  [1. 1. 1.]


### 4) Dot product 

In [10]:
# vector dot product
from numpy import array
# define first vector
a = array([1, 2, 3])
print(" The  first vector is :",a)
# define second vector
b = array([1, 2, 3])
print(" The second vector is : ",b)
# multiply vectors
c = a.dot(b)
print(" c = a dot b is : ", c)  

 The  first vector is : [1 2 3]
 The second vector is :  [1 2 3]
 c = a dot b is :  14


### 5)  Vector Scalar Multiplication 

In [15]:
# vector-scalar multiplication
from numpy import array
# define vector
a = array([1, 2, 3])
print("Vector is : ",a)
# define scalar
s = 0.5
print("Scalar is ",s)
# multiplication
c = s * a
print(" c = s*a   is: ",c)


Vector is :  [1 2 3]
Scalar is  0.5
 c = s*a   is:  [0.5 1.  1.5]


### 6) L1 norm 

In [21]:
# Vector L1 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print("Vector a is : ", a)
# calculate norm
l1 = norm(a, 1)
print("The L1 norm of a is : ", l1)

Vector a is :  [1 2 3]
The L1 norm of a is :  6.0


### 7) L2 norm 

In [23]:
# vector L2 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print("The vector a is :",a)
# calculate norm
l2 = norm(a)
print("The l2 norm of a is :",l2)

The vector a is : [1 2 3]
The l2 norm of a is : 3.7416573867739413


## Matrices 

### Create  a   Matrix 

In [24]:
# create matrix
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


### Matrix addition 

In [28]:
# matrix addition
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print("Matrix A is :",A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print("Matrix B is :", B)
# add matrices
C = A + B
print(" Matrix C = A + B  is :", C)

Matrix A is : [[1 2 3]
 [4 5 6]]
Matrix B is : [[1 2 3]
 [4 5 6]]
 Matrix C = A + B  is : [[ 2  4  6]
 [ 8 10 12]]


###  Matrix subtraction 

In [31]:
# matrix subtraction
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print("Matrix A is ", A)
# define second matrix
B = array([
[0.5, 0.5, 0.5],
[0.5, 0.5, 0.5]])
print("Matrix B is ",B)
# subtract matrices
C = A - B
print("Matrix C = A-B is : ",C)

Matrix A is  [[1 2 3]
 [4 5 6]]
Matrix B is  [[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
Matrix C = A-B is :  [[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


### Matrix Multiplication : Element wise : Hadamard product 

In [ ]:
# matrix Hadamard product
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print("A matrix is : ", A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print("B matrix is :",B)
# multiply matrices
C = A * B
print

### Matrix Division 

In [33]:
# matrix division
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print("A matrix is : ",A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print("B  Matrix is : ",B)
# divide matrices
C = A / B
print("C = A/B", C)

A matrix is :  [[1 2 3]
 [4 5 6]]
B  Matrix is :  [[1 2 3]
 [4 5 6]]
C = A/B [[1. 1. 1.]
 [1. 1. 1.]]


### Matrix dot product 

In [ ]:
# matrix dot product
from numpy import array
# define first matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = array([
[1, 2],
[3, 4]])
print(B)
# multiply matrices
C = A.dot(B)
print(C)
# multiply matrices with @ operator
D = A @ B
print(D)

##  Matrix vector multiplication 

In [ ]:
# matrix-vector multiplication
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print("A  matrix is : ",A)
# define vector
B = array([0.5, 0.5])
print(" Vector is : ", B)
# multiply
C = A.dot(B)
print(" C = A dot B is : ",C)

###  Matrix Scalar Multiplication 

In [35]:
# matrix-scalar multiplication
from numpy import array
# define matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("matrix A is : ", A)
# define scalar
b = 0.5
print("scalar b is :", b)
# multiply
C = A * b
print(" C = A*b",C)

matrix A is :  [[1 2]
 [3 4]
 [5 6]]
scalar b is : 0.5
 C = A*b [[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


## Matrix types 

In [37]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(" Square matrix M is : \n ",M)
# lower triangular matrix
lower = tril(M)
print(" Lower triangular is :\n", lower)
# upper triangular matrix
upper = triu(M)
print(" Upper triangular is: \n", upper)


 Square matrix M is : 
  [[1 2 3]
 [1 2 3]
 [1 2 3]]
 Lower triangular is :
 [[1 0 0]
 [1 2 0]
 [1 2 3]]
 Upper triangular is: 
 [[1 2 3]
 [0 2 3]
 [0 0 3]]


In [39]:
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print("Square matrix M is \n ",M)
# extract diagonal vector
d = diag(M)
print("Diagonal vector is d \n ",d)
# create diagonal matrix from vector
D = diag(d)
print("Diagonal matrix is \n",D)

Square matrix M is 
  [[1 2 3]
 [1 2 3]
 [1 2 3]]
Diagonal vector is d 
  [1 2 3]
Diagonal matrix is 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [40]:
# identity matrix
from numpy import identity
I = identity(3)
print("Identity matrix is : I \n",I)

Identity matrix is : I 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
# orthogonal matrix
from numpy import array
from numpy.linalg import inv
# define orthogonal matrix
Q = array([
[1, 0],
[0, -1]])
print("Orthogonal Matrix is : \n",Q)
# inverse equivalence
V = inv(Q)
print(" Inverse  of Q is : \n ",V)
# get Transpose 
QT = Q.T
print("Transpose of Q is : \n",QT)
# identity equivalence
I = Q.dot(Q.T)
print("Q.QT is \n ",I)

Orthogonal Matrix is : 
 [[ 1  0]
 [ 0 -1]]
 Inverse  of Q is : 
  [[ 1.  0.]
 [-0. -1.]]
Transpose of Q is : 
 [[ 1  0]
 [ 0 -1]]
Q.QT is 
  [[1 0]
 [0 1]]


## Matrix operations 

In [45]:
# transpose matrix
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print("A is : \n",A)
# calculate transpose
C = A.T
print("A Transpose is : \n",C)

A is : 
 [[1 2]
 [3 4]
 [5 6]]
A Transpose is : 
 [[1 3 5]
 [2 4 6]]


In [46]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print("A matrix is : \n",A)
# invert matrix
B = inv(A)
print(" B is the inverse of A; B is: \n ",B)
# multiply A and B
I = A.dot(B)
print("A.B is : \n ",I)

A matrix is : 
 [[1. 2.]
 [3. 4.]]
 B is the inverse of A; B is: 
  [[-2.   1. ]
 [ 1.5 -0.5]]
A.B is : 
  [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [47]:
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print("A matrix is \n",A)
# calculate trace
B = trace(A)
print(" Trace of A  is \n",B)

A matrix is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 Trace of A  is 
 15


In [49]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print("A matrix is : \n",A)
# calculate determinant
B = det(A)
print("Determinant of A is : ",B)

A matrix is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of A is :  0.0


In [53]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rankn
print("First vector is: \n",v1)
vr1 = matrix_rank(v1)
print("Rank of First vector is : \n",vr1)
# zero rank
v2 = array([0,0,0,0,0])
print("A zero vector :\n", v2)
vr2 = matrix_rank(v2)
print("Rank of a zero vector is : \n",vr2)

First vector is: 
 [1 2 3]
Rank of First vector is : 
 1
A zero vector :
 [0 0 0 0 0]
Rank of a zero vector is : 
 0


In [55]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
[0,0]])
print("matrix M0 is : \n",M0)
mr0 = matrix_rank(M0)
print("Rank of M0 is : \n",mr0)
# rank 1
M1 = array([
[1,2],
[1,2]])
print("matrix M1 is : \n " ,M1)
mr1 = matrix_rank(M1)
print("rank of M1 is \n",mr1)
# rank 2
M2 = array([
[1,2],
[3,4]])
print("matrix  M2 is :\n",M2)
mr2 = matrix_rank(M2)
print("rank of M2 is : \n",mr2)


matrix M0 is : 
 [[0 0]
 [0 0]]
Rank of M0 is : 
 0
matrix M1 is : 
  [[1 2]
 [1 2]]
rank of M1 is 
 1
matrix  M2 is :
 [[1 2]
 [3 4]]
rank of M2 is : 
 2
